# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: umi

trigger:
  - master

jobs:
  - job: windows_test
    timeoutInMinutes: 30
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        node_8_x:
          node_version: 8.x
        node_10_x:
          node_version: 10.x
        node_12_x:
          node_version: 12.x
    steps:
      - checkout: self
        clean: all
        fetchDepth: 1
      - script: yarn install
        displayName: install
      - script: yarn build
        displayName: build
      - script: yarn test --forceExit --detectOpenHandles --runInBand
        env:
          PROGRESS: none
          CI: true
        displayName: test
