name: Node CI

on:
  push:
    paths-ignore:
      - '.github/**/*.md'
      - 'examples/**'
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.yarnpkg.com'
      - name: restore lerna
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --ignore-engines
      - run: yarn build
      - run: yarn run tsc --noEmit
      - run: yarn test --detectOpenHandles --maxWorkers=4 --forceExit
        env:
          CI: true
          HEADLESS: false
          PROGRESS: none
          NODE_ENV: test
