name: Deploy Doc Site
on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: website
      run: |
        cd ./website
    - name: deploy
      uses: actions/zeit-now@master
      with:
        args: --prod --scope umijs
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
