name: Outdated Version Action

on:
  push:
      paths-ignore:
        - '.github/**/*.md'
        - 'examples/**'
        - 'docs/**'
        - '*.md'

jobs:
  outdated-version:
    runs-on: ubuntu-latest
    steps:
      - name: outdated version
        uses: ycjcl868/outdated-version-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
